---
title: RHODAN
baseurl: "/Rhodan" 
  url: "https://KillSwitchX7.github.io"

exclude: ['/scripts', '/Gemfile', '/Makefile', '/README.md']

permalink: pretty

collections:
  tools:
    output: true

defaults:
  - scope:
      path: '_tools'
    values:
      layout: bin
